name: nvsf

networks:
  nvsf:
    driver: bridge

services:
  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile    # Dockerfile for Streamlit
      target: app_img           # Target of docker image for multi stage build
    image: app_img:latest
    ports:
      - 8501:8501             # Map port 8501 of the container to port 8501 on the host
    networks:
      - nvsf
    environment:
      - FASTAPI_URL=http://fastapi:8000  # Pass the FastAPI service URL as an environment variable
  
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile    # Dockerfile for FastAPI
      target: api_img           # Target of docker image for multi stage build
    image: api_img:latest
    # ports:
    #   - 8000:8000             # Map port 8000 of the container to port 8000 on the host
    volumes:
      - nvsf-api:/app           # Named volume to mount data
    networks:
      - nvsf
    # Optional: Add health check
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   retries: 3

volumes:
  nvsf-api:
    driver: local
