version: '3'
services:
  fastapi:
    image: api_img
    ports:
      - "8000:8000"
    networks:
      - my_network

  streamlit:
    image: app_img
    ports:
      - "8501:8501"
    networks:
      - my_network
    environment:
      - FASTAPI_URL=http://fastapi:8000  # Pass the FastAPI service URL as an environment variable

networks:
  my_network:
    driver: bridge
